name: notepad_pro
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path: ^1.8.0
  dots_indicator: ^3.0.0
  google_fonts: ^5.1.0
  meta: ^1.7.0
  provider: 6.1.1
  rename_app: ^1.3.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/onboarding1.png
    - assets/onBoarding2.png
    - assets/onBoarding3.png
